version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - 127.0.0.1:2379:2379
      - 127.0.0.1:2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_DATA_DIR=/data/data
      - ETCD_WAL_DIR=/data/wal
      - ETCD_NAME=etcd
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - data:/tmp/etcd-data
volumes:
  data: {}
