version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - 127.0.0.1:2379:2379
      - 127.0.0.1:2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_DATA_DIR=/data/data
      - ETCD_WAL_DIR=/data/wal
      - ETCD_NAME=etcd
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - data:/tmp/etcd-data
  scylla:
    image: scylladb/scylla
  request-router:
    image: sqrr:latest
    environment:
      - ETCD_HOSTS=etcd:2379
    ports:
      - 127.0.0.1:9090:9090
  sq1:
    build: ./
    depends_on:
      - scylla
    command:
      - /app/superQueue
      - -partition=sq1
      - -queue-len=1000000
      - -port=8080
      - -advertise-url=http://sq1:8080
      - -scylla-hosts=scylla:9042
      - -etcd-hosts=etcd:2379
  sq2:
    build: ./
    environment:
      - HTTP_PORT=8080
      - ETCD_HOSTS=etcd:2379
      - QUEUE_LEN=1000000
      - PARTITION=sq2
      - SCYLLA_HOSTS=scylla:9042
      - "ADVERTISE_URL=http://sq2:8080"
    depends_on:
      - scylla
volumes:
  data: {}
