apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sq-ss
  labels:
    app: sq
spec:
  replicas: 1
  serviceName: sq
  selector:
    matchLabels:
      app: sq
  template:
    metadata:
      labels:
        app: sq
    spec:
      containers:
        - name: sq
          image: $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/sq:$SEM_VER
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/app/superQueue"]
          args:
            - -partition=$MY_POD_NAME
            - -queue-len=1000000
            - -port=8080
            - -advertise-url="http://$MY_POD_NAME.sq.default.svc.cluster.local:8080"
            - -scylla-hosts=scylla.default.svc.cluster.local:9042
            - -etcd-hosts=etcd.default.svc.cluster.local:2379
          resources:
            requests:
              memory: '1024M'
              cpu: '1'
            limits:
              memory: '2048M'
              cpu: "1"
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sq-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app: sq
