apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sq-ss
  labels:
    app: sq
spec:
  replicas: 4
  serviceName: sq-service
  selector:
    matchLabels:
      app: sq
  template:
    metadata:
      labels:
        app: sq
    spec:
      containers:
        - name: sq
          image: danthegoodman1/superqueue:0.1
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/app/superQueue"]
          args:
            - -partition=$(MY_POD_NAME)
            - -queue-len=1000000
            - -port=8080
            - -advertise-url=http://$(MY_POD_NAME).sq-service.default.svc.cluster.local:8080
            - -scylla-hosts=scylla-0.scylla-service.default.svc.cluster.local:9042
            - -etcd-hosts=etcd-0.etcd-service.default.svc.cluster.local:2379
          resources:
            requests:
              memory: '1024M'
              cpu: '1'
            limits:
              memory: '1024M'
              cpu: "1"
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sq-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app: sq
